import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = [
  readFileSync(new URL('./api-emulator/src/index.ts', import.meta.url), 'utf8'),
  readFileSync(new URL('./api-emulator/src/routes/http.ts', import.meta.url), 'utf8'),
].join('\n');

const requiredRoutes = [
  '/v2/account',
  '/v2/clock',
  '/v2/positions',
  '/v2/positions/:symbol',
  '/v2/positions/:symbol/exercise',
  '/v2/orders',
  '/v2/orders:by_client_order_id',
  '/v2/orders/:orderId',
  '/v2/account/portfolio/history',
  '/v2/account/configurations',
  '/v2/calendar',
  '/v2/assets',
  '/v2/assets/:symbol',
  '/v2/watchlists',
  '/v2/watchlists/:watchlistId',
  '/v2/watchlists/:watchlistId/:symbol',
  '/v2/corporate_actions/announcements',
  '/v2/corporate_actions/announcements/:corporateActionId',
  '/v2/options/contracts',
  '/v2/options/contracts/:symbol',
  '/v2/stocks/bars',
  '/v2/stocks/:symbol/bars',
  '/v2/stocks/quotes',
  '/v2/stocks/trades',
  '/v2/stocks/trades/latest',
  '/v2/stocks/quotes/latest',
  '/v2/stocks/bars/latest',
  '/v2/stocks/snapshots',
  '/v2/stocks/:symbol/snapshot',
  '/v1beta3/crypto/:feed/bars',
  '/v1beta3/crypto/:feed/quotes',
  '/v1beta3/crypto/:feed/trades',
  '/v1beta3/crypto/:feed/latest/trades',
  '/v1beta3/crypto/:feed/latest/quotes',
  '/v1beta3/crypto/:feed/latest/bars',
  '/v1beta3/crypto/:feed/latest/orderbooks',
  '/v1beta3/crypto/:feed/snapshots',
  '/v1beta1/options/bars',
  '/v1beta1/options/meta/exchanges',
  '/v1beta1/options/quotes/latest',
  '/v1beta1/options/trades/latest',
  '/v1beta1/options/trades',
  '/v1beta1/options/snapshots',
  '/v1beta1/options/snapshots/:underlyingSymbol',
  '/v1beta1/news',
  '/v1beta1/corporate-actions',
  '/v1beta1/screener/stocks/most-actives',
  '/v1beta1/screener/stocks/movers',
  '/v1beta1/screener/crypto/movers',
  '/v1/accounts',
  '/v1/accounts/activities',
  '/v1/accounts/positions',
  '/v1/accounts/:accountId',
  '/v1/accounts/:accountId/actions/close',
  '/v1/accounts/:accountId/documents',
  '/v1/accounts/:accountId/documents/upload',
  '/v1/accounts/:accountId/documents/:documentId',
  '/v1/accounts/:accountId/documents/:documentId/download',
  '/v1/accounts/:accountId/ach_relationships',
  '/v1/accounts/:accountId/ach_relationships/:relationshipId',
  '/v1/accounts/:accountId/recipient_banks',
  '/v1/accounts/:accountId/recipient_banks/:bankId',
  '/v1/accounts/:accountId/transfers',
  '/v1/accounts/:accountId/transfers/:transferId',
  '/v1/trading/accounts/:accountId/account',
  '/v1/trading/accounts/:accountId/account/configurations',
  '/v1/trading/accounts/:accountId/positions',
  '/v1/trading/accounts/:accountId/positions/:symbol',
  '/v1/trading/accounts/:accountId/positions/:symbol/exercise',
  '/v1/trading/accounts/:accountId/account/portfolio/history',
  '/v1/trading/accounts/:accountId/watchlists',
  '/v1/trading/accounts/:accountId/watchlists/:watchlistId',
  '/v1/trading/accounts/:accountId/watchlists/:watchlistId/:symbol',
  '/v1/trading/accounts/:accountId/orders',
  '/v1/trading/accounts/:accountId/orders:by_client_order_id',
  '/v1/trading/accounts/:accountId/orders/:orderId',
  '/v1/clock',
  '/v1/calendar',
  '/v1/assets',
  '/v1/assets/:symbol',
  '/v1/journals',
  '/v1/journals/batch',
  '/v1/journals/reverse_batch',
  '/v1/journals/:journalId',
  '/v1/corporate_actions/announcements',
  '/v1/corporate_actions/announcements/:corporateActionId',
  '/v1/corporate-actions',
  '/v1/events/accounts/status',
  '/v1/events/trades',
  '/v1/events/journals/status',
  '/v1/events/transfers/status',
  '/v1/events/nta',
  '/v1/rebalancing/portfolios',
  '/v1/rebalancing/portfolios/:portfolioId',
  '/v1/rebalancing/subscriptions',
  '/v1/rebalancing/subscriptions/:subscriptionId',
  '/v1/rebalancing/runs',
  '/v1/rebalancing/runs/:runId',
];

for (const route of requiredRoutes) {
  assert.ok(source.includes(route), `missing Alpaca route ${route}`);
}

console.log('alpaca smoke ok');
