export const WORKSPACE_SERVICES = [
  { alias: 'drive', api: 'drive', version: 'v3', serviceId: 'drive.googleapis.com' },
  { alias: 'sheets', api: 'sheets', version: 'v4', serviceId: 'sheets.googleapis.com' },
  { alias: 'gmail', api: 'gmail', version: 'v1', serviceId: 'gmail.googleapis.com' },
  { alias: 'calendar', api: 'calendar', version: 'v3', serviceId: 'calendar-json.googleapis.com' },
  { alias: 'docs', api: 'docs', version: 'v1', serviceId: 'docs.googleapis.com' },
  { alias: 'slides', api: 'slides', version: 'v1', serviceId: 'slides.googleapis.com' },
  { alias: 'tasks', api: 'tasks', version: 'v1', serviceId: 'tasks.googleapis.com' },
  { alias: 'people', api: 'people', version: 'v1', serviceId: 'people.googleapis.com' },
  { alias: 'chat', api: 'chat', version: 'v1', serviceId: 'chat.googleapis.com' },
  { alias: 'vault', api: 'vault', version: 'v1', serviceId: 'vault.googleapis.com' },
  { alias: 'groupssettings', api: 'groupssettings', version: 'v1', serviceId: 'groupssettings.googleapis.com' },
  { alias: 'reseller', api: 'reseller', version: 'v1', serviceId: 'reseller.googleapis.com' },
  { alias: 'licensing', api: 'licensing', version: 'v1', serviceId: 'licensing.googleapis.com' },
  { alias: 'script', api: 'script', version: 'v1', serviceId: 'script.googleapis.com' },
  { alias: 'admin', api: 'admin', version: 'directory_v1', serviceId: 'admin.googleapis.com' },
  { alias: 'reports', api: 'admin', version: 'reports_v1', serviceId: 'admin.googleapis.com' },
  { alias: 'classroom', api: 'classroom', version: 'v1', serviceId: 'classroom.googleapis.com' },
  { alias: 'cloudidentity', api: 'cloudidentity', version: 'v1', serviceId: 'cloudidentity.googleapis.com' },
  { alias: 'alertcenter', api: 'alertcenter', version: 'v1beta1', serviceId: 'alertcenter.googleapis.com' },
  { alias: 'forms', api: 'forms', version: 'v1', serviceId: 'forms.googleapis.com' },
  { alias: 'keep', api: 'keep', version: 'v1', serviceId: 'keep.googleapis.com' },
  { alias: 'meet', api: 'meet', version: 'v2', serviceId: 'meet.googleapis.com' },
  { alias: 'workspaceevents', api: 'workspaceevents', version: 'v1', serviceId: 'workspaceevents.googleapis.com' },
  { alias: 'pubsub', api: 'pubsub', version: 'v1', serviceId: 'pubsub.googleapis.com' },
];
