import { branch as createMysqlBranch, connectionConfig, createDatabase, deleteBranch, diffBranch, execSql, exportBranch, promoteBranch } from '../../local-mysql/branch.mjs';

function now() { return new Date().toISOString(); }
function id(prefix) { return prefix + '_' + crypto.randomUUID().replaceAll('-', '').slice(0, 20); }
function state(store) {
  const key = 'planetscale:state';
  const existing = store.getData?.(key);
  if (existing) return existing;
  const initial = { organizations: [], databases: [], branches: [], passwords: [], deployRequests: [] };
  store.setData?.(key, initial);
  return initial;
}
function save(store, next) { store.setData?.('planetscale:state', next); }
async function body(c) {
  if (c.req.parseBody) return c.req.parseBody().catch(() => ({}));
  return c.req.json().catch(() => ({}));
}
function list(items) { return { data: items, pagination: { total: items.length } }; }
function physicalDatabaseName(...parts) {
  const value = parts.join('_').replaceAll('-', '_').replaceAll('.', '_').replace(/[^a-zA-Z0-9_]/g, '_').slice(0, 58);
  return `ps_${value}`.slice(0, 63);
}
function databaseRecord(next, org, database) {
  return next.databases.find((item) => item.organization === org && item.name === database);
}
function branchRecord(next, org, database, branch) {
  return next.branches.find((item) => item.organization === org && item.database === database && item.name === branch);
}

export function registerRoutes(app, store, contract) {
  app.get('/organizations', (c) => c.json(list(state(store).organizations)));
  app.post('/organizations/:org/databases', async (c) => { const next = state(store); const input = await body(c); if (!next.organizations.find((o) => o.name === c.req.param('org'))) next.organizations.push({ name: c.req.param('org') }); const name = input.name ?? 'emulator-db'; const db = { id: id('db'), organization: c.req.param('org'), name, database_name: physicalDatabaseName(c.req.param('org'), name, 'main'), created_at: now() }; await createDatabase(db.database_name); next.databases = next.databases.filter((item) => item.organization !== db.organization || item.name !== db.name); next.databases.push(db); save(store, next); return c.json(db, 201); });
  app.get('/organizations/:org/databases', (c) => c.json(list(state(store).databases.filter((d) => d.organization === c.req.param('org')))));
  app.post('/organizations/:org/databases/:database/branches', async (c) => { const next = state(store); const input = await body(c); const parent = input.parent ?? input.parent_branch ?? input.parentBranch; const db = databaseRecord(next, c.req.param('org'), c.req.param('database')); if (!db) return c.json({ error: 'not_found', message: 'Database not found' }, 404); const sourceBranch = parent ? branchRecord(next, c.req.param('org'), c.req.param('database'), parent) : null; const source = sourceBranch?.database_name ?? db.database_name; const name = input.name ?? 'main'; const target = physicalDatabaseName(c.req.param('org'), c.req.param('database'), name); const branch = { id: id('branch'), organization: c.req.param('org'), database: c.req.param('database'), name, database_name: target, safe_migrations: true, created_at: now() }; await createMysqlBranch(source, target); next.branches = next.branches.filter((item) => item.organization !== branch.organization || item.database !== branch.database || item.name !== branch.name); next.branches.push(branch); save(store, next); return c.json(branch, 201); });
  app.get('/organizations/:org/databases/:database/branches', (c) => c.json(list(state(store).branches.filter((b) => b.database === c.req.param('database')))));
  app.post('/organizations/:org/databases/:database/branches/:branch/passwords', async (c) => { const next = state(store); const input = await body(c); const target = branchRecord(next, c.req.param('org'), c.req.param('database'), c.req.param('branch')); if (!target) return c.json({ error: 'not_found', message: 'Branch not found' }, 404); const credentials = connectionConfig(target.database_name); const pass = { id: id('pwd'), name: input.name ?? 'default', username: credentials.username, password: credentials.password, host: credentials.host, port: credentials.port, database: credentials.database, branch: c.req.param('branch') }; next.passwords.push(pass); save(store, next); return c.json(pass, 201); });
  app.post('/organizations/:org/databases/:database/deploy-requests', async (c) => { const next = state(store); const input = await body(c); const sourceName = input.branch ?? input.source_branch ?? input.sourceBranch; const targetName = input.into_branch ?? input.target_branch ?? input.targetBranch ?? 'main'; const source = sourceName ? branchRecord(next, c.req.param('org'), c.req.param('database'), sourceName) : null; const target = branchRecord(next, c.req.param('org'), c.req.param('database'), targetName) ?? databaseRecord(next, c.req.param('org'), c.req.param('database')); const diff = source && target ? await diffBranch(source.database_name, target.database_name) : null; const dr = { id: id('dr'), database: c.req.param('database'), state: 'open', branch: sourceName ?? null, into_branch: targetName, diff, created_at: now() }; next.deployRequests.push(dr); save(store, next); return c.json(dr, 201); });
  app.post('/organizations/:org/databases/:database/deploy-requests/:deployRequest/deploy', async (c) => { const next = state(store); const deployRequest = next.deployRequests.find((item) => item.id === c.req.param('deployRequest')); if (!deployRequest) return c.json({ error: 'not_found', message: 'Deploy request not found' }, 404); const source = deployRequest.branch ? branchRecord(next, c.req.param('org'), c.req.param('database'), deployRequest.branch) : null; const target = branchRecord(next, c.req.param('org'), c.req.param('database'), deployRequest.into_branch) ?? databaseRecord(next, c.req.param('org'), c.req.param('database')); if (!source || !target) return c.json({ error: 'not_found', message: 'Deploy source or target not found' }, 404); await promoteBranch(source.database_name, target.database_name); deployRequest.state = 'deployed'; deployRequest.deployed_at = now(); save(store, next); return c.json(deployRequest); });
  app.post('/_emu/planetscale/branches/:branch/exec', async (c) => { const next = state(store); const target = next.branches.find((item) => item.name === c.req.param('branch') || item.database_name === c.req.param('branch')); const input = await body(c); if (!target) return c.json({ error: 'not_found' }, 404); return c.json({ stdout: await execSql(target.database_name, input.sql ?? '') }); });
  app.get('/_emu/planetscale/branches/:branch/diff', async (c) => { const next = state(store); const target = next.branches.find((item) => item.name === c.req.param('branch') || item.database_name === c.req.param('branch')); if (!target) return c.json({ error: 'not_found' }, 404); const parent = c.req.query?.('parent') ?? databaseRecord(next, target.organization, target.database)?.database_name ?? 'app_main'; return c.json(await diffBranch(target.database_name, parent)); });
  app.post('/_emu/db/planetscale/databases', async (c) => { const next = state(store); const input = await body(c); const org = input.organization ?? input.org ?? 'emulator'; if (!next.organizations.find((item) => item.name === org)) next.organizations.push({ name: org }); const name = input.name ?? input.id ?? 'emulator_db'; const db = { id: id('db'), organization: org, name, database_name: physicalDatabaseName(org, name, 'main'), created_at: now() }; await createDatabase(db.database_name); next.databases = next.databases.filter((item) => item.organization !== org || item.name !== name); next.databases.push(db); save(store, next); return c.json(db, 201); });
  app.get('/_emu/db/planetscale/databases', (c) => c.json({ data: state(store).databases }));
  app.post('/_emu/db/planetscale/databases/:id/branches', async (c) => { const next = state(store); const input = await body(c); const db = next.databases.find((item) => item.id === c.req.param('id') || item.name === c.req.param('id')); if (!db) return c.json({ error: 'not_found', message: 'Database not found' }, 404); const parent = input.parent ?? input.parent_branch ?? input.parentBranch; const sourceBranch = parent ? branchRecord(next, db.organization, db.name, parent) : null; const source = sourceBranch?.database_name ?? db.database_name; const name = input.name ?? input.branch ?? 'main'; const target = physicalDatabaseName(db.organization, db.name, name); const branch = { id: id('branch'), organization: db.organization, database: db.name, name, database_name: target, safe_migrations: true, created_at: now() }; await createMysqlBranch(source, target); next.branches = next.branches.filter((item) => item.organization !== branch.organization || item.database !== branch.database || item.name !== branch.name); next.branches.push(branch); save(store, next); return c.json(branch, 201); });
  app.get('/_emu/db/planetscale/databases/:id/branches', (c) => { const next = state(store); const db = next.databases.find((item) => item.id === c.req.param('id') || item.name === c.req.param('id')); return c.json({ data: db ? next.branches.filter((branch) => branch.organization === db.organization && branch.database === db.name) : [] }); });
  app.delete?.('/_emu/db/planetscale/databases/:id/branches/:branch', async (c) => { const next = state(store); const target = next.branches.find((item) => item.name === c.req.param('branch') || item.database_name === c.req.param('branch')); if (!target) return c.json({ error: 'not_found' }, 404); await deleteBranch(target.database_name); next.branches = next.branches.filter((item) => item.id !== target.id); save(store, next); return c.json({ ok: true }); });
  app.post('/_emu/db/planetscale/databases/:id/branches/:branch/exec', async (c) => { const next = state(store); const target = next.branches.find((item) => item.name === c.req.param('branch') || item.database_name === c.req.param('branch')); const input = await body(c); if (!target) return c.json({ error: 'not_found' }, 404); return c.json({ stdout: await execSql(target.database_name, input.sql ?? '') }); });
  app.get('/_emu/db/planetscale/databases/:id/branches/:branch/export', async (c) => { const target = state(store).branches.find((item) => item.name === c.req.param('branch') || item.database_name === c.req.param('branch')); if (!target) return c.json({ error: 'not_found' }, 404); return c.json({ sql: await exportBranch(target.database_name) }); });
  app.get('/_emu/db/planetscale/databases/:id/branches/:branch/diff', async (c) => { const next = state(store); const target = next.branches.find((item) => item.name === c.req.param('branch') || item.database_name === c.req.param('branch')); const db = next.databases.find((item) => item.id === c.req.param('id') || item.name === c.req.param('id')); if (!target || !db) return c.json({ error: 'not_found' }, 404); return c.json(await diffBranch(target.database_name, db.database_name)); });
  app.post('/_emu/db/planetscale/databases/:id/branches/:branch/promote', async (c) => { const next = state(store); const target = next.branches.find((item) => item.name === c.req.param('branch') || item.database_name === c.req.param('branch')); const db = next.databases.find((item) => item.id === c.req.param('id') || item.name === c.req.param('id')); if (!target || !db) return c.json({ error: 'not_found' }, 404); await promoteBranch(target.database_name, db.database_name); return c.json({ ok: true }); });
  app.get('/inspect/contract', (c) => c.json(contract));
  app.get('/inspect/state', (c) => c.json(state(store)));
  app.post('/inspect/reset', (c) => { store.setData?.('planetscale:state', null); state(store); return c.json({ ok: true }); });
}
